name: Earthly CI

on:
  push:

jobs:
  ci:
    name: Earthly CI
    runs-on: ubuntu-latest
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      SATELLITE_NAME: shepherdjerred.com
    steps:
      - uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Docker login
        run: docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: Run for dev
        if: github.ref == 'refs/heads/main' && github.action == 'push'
        run: earthly --ci --push +ci --prod=false
      - name: Run for prod
        if: github.ref == 'refs/heads/main' && github.action == 'push'
        run: earthly --ci --push +ci --prod=true
